### ISSUE TITLE
require() is nil?

### ISSUE THREAD

**Issue by slembcke** [aseprite/api#10]
Is there any reason to disallow the package system? I could probably get by with `loadfile()`, but it would require me to hard code system specific paths into my scripts.

**Comment by dacap** [comment]
Known issue. At the moment I didn't export the `require()` keyboard just for lack of time to learn more about it, but I hope to implement this in the near future.

**Comment by WilliamIzzo83** [comment]
Yeah this could be most usefult to write extension to lua, or to use the _struct_ module which helps to write binary files
