### ISSUE TITLE
drawImage() does not draw properly transparent colors

### ISSUE THREAD

**Issue by ppelikan** [aseprite/api#102]
We draw an yellow X on the `Layer 2` (and the rest is on the `Layer 1`):
![Screenshot_20230428_002504](https://user-images.githubusercontent.com/6893111/235004108-2452bf66-d106-4ceb-b44e-d1d549e2d37c.png)
Now if we want to draw all layers from `Group 1` using API call `drawImage()` with an example code:
```
local layer = app.activeSprite.layers[1]
local bufimg = Image(app.activeSprite.width, app.activeSprite.height, ColorMode.RGB)
if layer.layers ~= nil then
    for _,l in ipairs(layer.layers) do
        local ce = l:cel(app.activeFrame.frameNumber)
        if ce ~= nil then
            bufimg:drawImage(ce.image, ce.position, ce.opacity) --, l.blendMode)
        end
    end
end

local new_layer = app.activeSprite:newLayer()
local new_cel = app.activeSprite:newCel(new_layer, app.activeFrame.frameNumber)
new_cel.image:drawImage(bufimg)
```
we get the following result on the new `Layer`:
![Screenshot_20230428_002556](https://user-images.githubusercontent.com/6893111/235004213-9abff0c1-2eaa-4504-8f68-9824da6f405b.png)

It seems that the transparent color was disregarded, and treated as any other color.
I would expect the yellow X to be drawn the same way as on the first picture.
Is it a bug of the `drawImage()` itself?

Aseprite version 1.2.40

**Comment by Gasparoken** [comment]
Thank you for this detailed report. That is normal behavior in 1.2.40. But in the latest version (1.3rc2) we added blending options to this function at https://github.com/aseprite/aseprite/commit/637632eafbfb052ea3b6e18b6764c75e88c00e9e.
We'll need to add some version compatibility statement when new options are added.

**Comment by Gasparoken** [comment]
> How can I ensure that merging layers works correctly?
With a script that compares images pixel by pixel:
Control image (created manually from two source images) VS image resulting from drawImage() (same two source images).

> Does it mean, that updating to this version and using BlendMode.NORMAL would fix this problem?
Yes. But you don't need to add BlendMode.NORMAL as an argument because it's the default blend mode.
