### ISSUE TITLE
app.transaction() not functional

### ISSUE THREAD

**Issue by GunTurtle** [aseprite/api#18]
Defining a function and executing it via app.transaction() does not group all operations in the function as one modification to the sprite, but instead defines the "transaction" as its own undo step while keeping everything in the function separate.
`
function drawstuff()
	app.useTool{
		tool="rectangle",
		brush=Brush(1),
		points={Point(40,10),Point(80,80)}
	}
	app.useTool{
		tool="rectangle",
		brush=Brush(1),
		points={Point(90,30),Point(110,80)}
	}
end`
`app.transaction(drawstuff)`

**Comment by dacap** [comment]
It looks like a bug of `app.useTool()` which is creating a new transaction instead of using the `app.transaction()`. I'll try to fix it in the next version.
