### ISSUE TITLE
pixelColor.rgba returns an "inverted" number

### ISSUE THREAD

**Issue by Sephi-Chan** [aseprite/api#2]
Hi!

As of today (2018-11-04 version 1.2.10-beta2) the app.pixelColor.rgba functions doesn't work as expected. The returned value is reversed from red, green, blue, alpha to alpha, blue, green, red.

``` lua
local yellow = pc.rgba(255, 255, 0, 255)
print("Yellow:")
print("pc.rgba(255, 255, 0) = " .. yellow) -- 4278255615 aka FF00FFFF aka some pink.
print("red: " .. pc.rgbaR(yellow))
print("green: " .. pc.rgbaG(yellow))
print("blue: " .. pc.rgbaB(yellow))
print("\n")

local real_yellow = pc.rgba(255, 0, 255, 255) -- in the ABGR order.
print("Real yellow:")
print("pc.rgba(255, 0, 255, 255) = " .. real_yellow) -- 4294902015 aka FFFF00FF aka yellow
print("red: " .. pc.rgbaR(real_yellow))
print("green: " .. pc.rgbaG(real_yellow))
print("blue: " .. pc.rgbaB(real_yellow))
```

Have a nice day!

**Comment by dacap** [comment]
Actually this is working as expected. Basically you cannot trust the integer value of a pixel color (only for indexed mode you can trust it). On RGBA values you can trust that rgbaR() will return the red component, rgbaG() the green, etc.

The order of the uint32 bits might vary depending of the platform ([little-endian](https://en.wikipedia.org/wiki/Endianness#Little-endian), [big-endian](https://en.wikipedia.org/wiki/Endianness#Big-endian) or in the future, depending of the default/preferred display RGB/BGR order to make the faster rendering possible. So you shouldn't use/expected that the uint32 value of a pixelColor will be always the same (trust only in `pixelColor.rgba*` functions).

**Comment by Sephi-Chan** [comment]
Thanks!
