### ISSUE TITLE
Exporting Pixels data to a different File format

### ISSUE THREAD

**Issue by gachis** [aseprite/api#25]
Hi,

first of all, thank you for this api, I'm experimenting on LUA, I'm working on a script where I read pixels data on a given sprite and I wanted to save the pixels informations I need in a .txt file for my game

So I tried to use

```
local file = io.open(path.."test.txt", "w+")
file:write('test')
file:close()
```

After allowing the writing access
<img width="856" alt="Capture d’écran 2020-04-17 à 14 02 27" src="https://user-images.githubusercontent.com/20369081/79567536-b194a980-80b4-11ea-9b2c-0b2806aa4a6f.png">

I get a nil value from file 
<img width="1248" alt="Capture d’écran 2020-04-17 à 14 02 36" src="https://user-images.githubusercontent.com/20369081/79567548-b8232100-80b4-11ea-8a0a-980204f0f095.png">

Am I missing something?

**Comment by dacap** [comment]
Hi @gachis, I've just tried on macOS and it works, I'll try to check on Windows, maybe it's a platform-specific bug.

**Comment by gachis** [comment]
Arg, i'm on macOS Yosemite...

**Comment by dacap** [comment]
Oh sorry I don't know why I thought it was on Windows.

Just in case, check that the `path` variable has a `/` at the end, or use `app.fs.joinPath(path, 'test')` in other case. That might be a problem.

**Comment by dacap** [comment]
Other thing I can think of is something related to permissions (e.g. the user running the Aseprite instance doesn't have write access to the specific folder). But I guess that you are writing the file inside/in a subfolder of your $HOME dir.

**Comment by gachis** [comment]
Thank you it was the missing `/` !!
