### ISSUE TITLE
Add blend mode to drawImage()

### ISSUE THREAD

**Issue by dacap** [aseprite/api#31]
`Image:drawImage()` should use NORMAL blend mode and we should be able to change this blending mode.

**Comment by SamanthaClarke1** [comment]
So, to clarify, since I can't read and am very stupid, this was canceled before the release of Aseprite v1.2.x, and is no longer planned for release?
Is there any news on when we might see this implemented, or released?

Sorry if I'm just reading your docs wrong, new to this codebase.

**Comment by dacap** [comment]
Hi there @SamanthaClarke1, this will be implemented sometime but it's not scheduled (so it's not planned in the short-term). We have plans to work exclusively on v1.3-beta1 and kicking everything else for the future.

**Comment by dacap** [comment]
This is already implemented.`BlendMode.SRC` can be used to copy pixels directly and `BlendMode.NORMAL` is the default behavior. Anyway there are a couple of bugs: 

* https://github.com/aseprite/aseprite/issues/4530
* https://github.com/aseprite/aseprite/issues/4531
