### ISSUE TITLE
Clarify how (and if) app.useTool works with selection

### ISSUE THREAD

**Issue by lampysprites** [aseprite/api#37]
The following code doesn't seem to select anything, although similar calls work fine for drawing tools
```lua
app.preferences.selection.mode = 0 -- SelectionMode::NORMAL according to data/pref.xml
app.useTool{ tool="magic_wand", points={Point(10,10)} }
app.useTool{ tool="rectangular_marquee", points={Point(10,10), Point(20,20)} }
```
WAIDW?

**Comment by dacap** [comment]
Hi @lampysprites, it doesn't work yet, but we're going to add support for this in the next version (v1.2.28 and v1.3):

https://github.com/aseprite/api/blob/next-version/api/app.md#appusetool
