### ISSUE TITLE
Dialog Bounds in v1.3-Beta1

### ISSUE THREAD

**Issue by CarbsCode** [aseprite/api#40]
After doing a few tests it seems that with the new floating windows have made dialogs a bit broken.

When dialogs options (ie buttons / sliders etc. ) are shown or hidden the dialog does not resize up or down to fit the size of the newly shown or hidden options. It does look like internally the dialog sees that it needs to change sizes but the sizes are not reflected correctly to the dialog window that is rendering.

Trying to modify the dialogs bounds also seems to freeze the dialog making it unable to accept any input.

Here is my simple code that I'm using to test this. Let me know if maybe I'm doing something wrong even or if this might actually be a bug in the system?

https://pastebin.com/jb12MH81

Here is also a video of me doing the testing:
https://gyazo.com/daf7c1a2c3054dc3307d1b1fba43ff4b

You can also see what is happening here as well:
https://gyazo.com/c02bca0fb52e7b0441b5a696f07ab7b9

**Comment by CarbsCode** [comment]
This was fixed in 1.3 Beta3 Thank you!

**Comment by dacap** [comment]
Glad to know it @CarbsCode 👍
