### ISSUE TITLE
`if data.ok` is confusing

### ISSUE THREAD

**Issue by jgollenz** [aseprite/api#45]
I just spend some time to figure out that the line 

`if data.ok then`

in the beginning of the documentation for the [dialog class](https://github.com/aseprite/api/blob/main/api/dialog.md#dialog) actually checks if the `ok` field of data is true. I thought that this might be some data consistency check or whatnot and that I always have to check if the data is actually ok, before I can access it. This is a beginner mistake, yes. But since this example is probably one of the first things people new to scripting will try out (making a hello world popup), it may happen to other beginners as well. 

Solution: just rename the `ok` id to `confirm`. This is also consistent with the other button that has the `cancel` id and is (imo) not as easily mistaken  with a mandatory data check.

**Comment by behreajj** [comment]
Yup. Thanks @jgollenz, wish I had realized this earlier.
