### ISSUE TITLE
Slider has `onchange`

### ISSUE THREAD

**Issue by jgollenz** [aseprite/api#47]
... but this is not reflected in [dialog.md](https://github.com/aseprite/api/blob/main/api/dialog.md#dialog). It's a nifty little feature, let's tell people about it

**Comment by jgollenz** [comment]
Apparently comboboxes do to. I'll adjust the PR accordingly

**Comment by dacap** [comment]
Thanks @jgollenz, I've just added the missing `,` to separate the fields.
