### ISSUE TITLE
Named Transactions For Undo History

### ISSUE THREAD

**Issue by behreajj** [aseprite/api#55]
Hello,

I have a feature request:

Would it be possible for `app.transaction` to accept an optional `string` argument so the transaction could be named? When the user runs a script, then wants to undo, they can open Undo History and have a better idea of what steps the script has taken. I realize that the user can already select a transaction in Undo History to see what state that would put in the image in, but some state changes may be less noticeable than others. To limit abuse, the string could have a minimum and maximum number of characters... or the `string` could follow a prefix. For example

```lua
app.transaction { name = "Foo", method = function() app.alert("Foo!") end }
```

could have the name "[Script] Foo" in the Undo History.

Thank you for considering!
Jeremy

**Comment by dacap** [comment]
Hi @behreajj, I've just found this issue by chance, this was implemented with https://github.com/aseprite/aseprite/commit/f536327fc1ff4d7a6ed0f4cca24db91c693b732b and is already available in v1.3-rc1 as:

```lua
app.transaction(string, function)
```
