### ISSUE TITLE
Duplicating frames in a layer?

### ISSUE THREAD

**Issue by bgreni** [aseprite/api#70]
I have no experience with lua, or aseprite, but a friend has asked me to write him a script to synchronize the frame durations of his sprite animations.

Basically all the frames are either 50, 100, or 200 ms long. He wishes to make them all 50ms, but in the case they are longer than that the solution is to duplicate the frames at 50ms. So a 100ms frame will become two 50ms frames. Any advice on how I can accomplish this? Thanks

**Comment by behreajj** [comment]
Hi @bgreni,

You may get more responses if you post your question at the [community forum](https://community.aseprite.org/) or on the scripting channel on Discord.

It sounds like you know the greatest common denominator (GCD) for this case: 50. However, I'd recommend generalizing. For that, find the GCD for an array of positive integers, then divide each number in the array by the GCD. The reduced ratio array represents the number of times a frame with an old duration will need to be duplicated with the new duration; the GCD is the new duration.

You may also wish to look at an `.aseprite` file from your friend to see if they use [group layers](https://github.com/aseprite/api/blob/main/api/layer.md#layerisgroup), as that is another potential major complication. (You may have to navigate hierarchies of child layers nested within parents for such a case.)

```lua
local function gcd(a, b)
    while b ~= 0 do a, b = b, a % b end
    return a
end

local function gcdArr(arr)
    local n = #arr
    local result = arr[1]
    for i = 1, n, 1 do
        result = gcd(result, arr[i])
    end
    return result
end

local function reduceArr(arr)
    local denom = gcdArr(arr)
    local n = #arr
    local result = {}
    for i = 1, n, 1 do
        result[i] = arr[i] // denom
    end
    return result, denom
end

local activeSprite = app.activeSprite
if activeSprite then
    local frames = activeSprite.frames
    local framesLen = #frames
    local durations = {}
    for i = 1, framesLen, 1 do
        local frame = frames[i]
        local durDecimal = frame.duration
        local duration = math.tointeger(durDecimal * 1000)
        durations[i] = duration
    end

    local multiples, newDuration = reduceArr(durations)
    print(string.format("new duration: %d", newDuration))
    for i = 1, framesLen, 1 do
        print(string.format(
            "old duration: %d, duplications: %d",
            durations[i], multiples[i]))
    end
end
```

There is a difference between how a frame's [duration](https://github.com/aseprite/api/blob/main/api/frame.md#frameduration) is stored and how it is displayed in the user interface. From storage to display, you need to multiply by 1000 and convert to an integer (truncate, round, floor).

New frames can be created with [sprite:newFrame()](https://github.com/aseprite/api/blob/main/api/sprite.md#spritenewframe) or [sprite:newEmptyFrame()](https://github.com/aseprite/api/blob/main/api/sprite.md#spritenewemptyframe). The primary content you'd be copying is an [image](https://github.com/aseprite/api/blob/main/api/image.md#image) held by a [cel](https://github.com/aseprite/api/blob/main/api/cel.md#cel), which _may_ be located at the intersection of a frame and a layer.

I don't think this script does what you're looking for, but might give you an example: [Prepare timeline to export for video editing - Frame Rat](https://community.aseprite.org/t/prepare-timeline-to-export-for-video-editing-frame-rat-v0-01-update-14-03-2021/8426). Note that some script writers prefer to work with [commands](https://github.com/behreajj/api/blob/main/api/app_command.md), others prefer working with the data directly.... And you may need to mix'n'match in rare cases. Your preference could make the job easier or harder, I don't know.

Good luck,
Jeremy
