### ISSUE TITLE
Add Lua API to access new UserData properties

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/api#88]
EDIT Just in case the following design was proposed by @dacap but there is no final API design, we have to talk about the best options.

Related to https://github.com/aseprite/aseprite/issues/3625

Add Lua API to access doc::UserData properties, e.g.

```lua
myLayer.extraData["extension id"].extensionCustomProperty or
myLayer.properties["extension id"].extensionCustomProperty
myLayer.extensionData["extension id"].extensionCustomProperty or
```

and probably

```lua
myLayer.userData.myProperty or
myLayer.userProperties.myProperty
```

as shortcut for

```lua
myLayer.extraData[""].myProperty
...
```

**Comment by dacap** [comment]
This depends on aseprite/aseprite#3631 and the API design must be discussed first.
