### ISSUE TITLE
Means to load and save Images directly

### ISSUE THREAD

**Issue by xentripetal** [aseprite/api#9]
Currently the only way to load an external Image into an already existing sprite is to use app.open([imagepath]) and extract the image from the associated cel and insert it into the existing sprite, then closing the temporary sprite with app.command.CloseFile().

The only way to extract an individual image seems to be to create a new sprite, insert the needed image, and use Sprite.SaveAs([path]).

If it does not break the API specs, it could be useful to have some means of importing and exporting Images directly from the Image class.

**Comment by dacap** [comment]
Added in
* https://github.com/aseprite/aseprite/commit/0bf5d1de308fbf789ae016618584adec6e4ae458
* https://github.com/aseprite/api/commit/6008f56f5c81eeb40fe3c4b5f321c10b80fb79d0

See docs: [Image{ fromFile }](https://github.com/aseprite/api/blob/next-version/api/image.md#image-1) and [Image:saveAs()
](https://github.com/aseprite/api/blob/next-version/api/image.md#imagesaveas)
